apiVersion: v1
kind: Service
metadata:
  name: k3s-golang
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30090
    protocol: TCP
    name: http
  selector:
    app: k3s-golang