apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k3s-flask
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k3s-flask
  template:
    metadata:
      labels:
        app: k3s-flask
    spec:
      containers:
        - name: k3s-flask
          image: index.docker.io/rpfeynman/k3s-flask:latest-2
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 250m
              memory: 256mi
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: k3s-flask
  namespace: default
spec:
  ports:
  - name: http
    targetPort: 80
    port: 80
  selector:
    app: k3s-flask
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: k3s-flask
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: k3s-flask.localhost
    http:
      paths:
      - path: /
        backend:
          serviceName: k3s-flask
          servicePort: http