---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: k3s-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: k3s-flask
          servicePort: 80