apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k3s-flask
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: k3s-flask
    spec:
      containers:
      - name: k3s-flask
        # Replace with your project ID
        image: gcr.io/poppy-88/flask-api
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 150m
            memory: 100Mi
        ports:
        - containerPort: 5000
