apiVersion: apps/v1
kind: Deployment
metadata:
  name: k3s-flask
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k3s-flask
  template:
    metadata:
      labels:
        app: k3s-flask
    spec:
      containers:
        - name: k3s-flask
          image: index.docker.io/rpfeynman/k3s-flask:latest-2
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 5000
