apiVersion: v1
kind: Service
metadata:
  name: k3s-flask
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30036
    protocol: TCP
    name: http
  selector:
    app: k3s-flask